[build]
  command = "pnpm install && pnpm build:web"
  publish = "dist/web"
  timeout = 900
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
