CREATE TABLE `estatisticasTemporada` (
	`id` int AUTO_INCREMENT NOT NULL,
	`atletaId` int NOT NULL,
	`userId` int NOT NULL,
	`temporada` varchar(20) NOT NULL DEFAULT '2025',
	`minutosJogados` int DEFAULT 0,
	`jogos` int DEFAULT 0,
	`jogosTitular` int DEFAULT 0,
	`gols` int DEFAULT 0,
	`assistencias` int DEFAULT 0,
	`finalizacoes` int DEFAULT 0,
	`desarmes` int DEFAULT 0,
	`interceptacoes` int DEFAULT 0,
	`duelos` int DEFAULT 0,
	`duelosGanhos` int DEFAULT 0,
	`passes` int DEFAULT 0,
	`passesCompletos` int DEFAULT 0,
	`cartoesAmarelos` int DEFAULT 0,
	`cartoesVermelhos` int DEFAULT 0,
	`notaTecnica` decimal(3,1),
	`notaFisica` decimal(3,1),
	`notaTatica` decimal(3,1),
	`notaAtitudinal` decimal(3,1),
	`notaPotencial` decimal(3,1),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `estatisticasTemporada_id` PRIMARY KEY(`id`)
);
