CREATE TABLE `jogos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`mandante` varchar(255) NOT NULL DEFAULT 'Marcílio Dias',
	`visitante` varchar(255) NOT NULL,
	`competicao` varchar(255),
	`data` date,
	`horario` varchar(10),
	`local` varchar(255),
	`arbitro` varchar(255),
	`assistente1` varchar(255),
	`assistente2` varchar(255),
	`renda` varchar(100),
	`publico` int,
	`gols` text,
	`placarMandante` int,
	`placarVisitante` int,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jogos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scoutJogo` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jogoId` int NOT NULL,
	`atletaId` int NOT NULL,
	`userId` int NOT NULL,
	`titular` boolean DEFAULT false,
	`minutosJogados` int DEFAULT 0,
	`gols` int DEFAULT 0,
	`assistencias` int DEFAULT 0,
	`finalizacoes` int DEFAULT 0,
	`passes` int DEFAULT 0,
	`passesCompletos` int DEFAULT 0,
	`desarmes` int DEFAULT 0,
	`interceptacoes` int DEFAULT 0,
	`duelos` int DEFAULT 0,
	`duelosGanhos` int DEFAULT 0,
	`jogosAereos` int DEFAULT 0,
	`duelosAereosPerdidos` int DEFAULT 0,
	`cartoesAmarelos` int DEFAULT 0,
	`cartoesVermelhos` int DEFAULT 0,
	`notaTecnica` decimal(3,1),
	`notaFisica` decimal(3,1),
	`notaTatica` decimal(3,1),
	`notaAtitudinal` decimal(3,1),
	`notaPotencial` decimal(3,1),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scoutJogo_id` PRIMARY KEY(`id`)
);
